### ISSUE TITLE
Dependencies declared using standard (non-mod) dependency types don't get added to Maven's pom.xml

### ISSUE THREAD

**Issue by The-Fireplace** [FabricMC/fabric-loom#419] opened 2021-06-19 23:50 UTC
When declaring dependencies on libraries that aren't mods, they don't get added to pom.xml when compile, implementation, api, and runtime are used. The workaround right now is to use the mod-augmented version (tested with `implementation` and `modImplementation`).

To reproduce:
1. Have a build.gradle set up with loom and maven-publish, like the fabric example mod.
2. Add `implementation "org.reflections:reflections:0.9.12"` to dependencies.
3. Run `gradle generatePomFileForMavenJavaPublication`
4. See that Reflections is not in the dependencies block of the generated pom.xml

Tested with Loom 0.8.20 on Gradle 7.0.2

**Comment by Juuxel** [comment] 2021-06-20 11:04
This is a duplicate of #200.

**Closed as completed** 2021-06-20 12:36 UTC
