### ISSUE TITLE
NullPointerException at ExternalResourceMetaData.getSha1() at SourceRemapper

### ISSUE THREAD

**Issue by teddyxlandlee** [FabricMC/fabric-loom#425] opened 2021-06-29 08:23 UTC
Minecraft version: any (especially 1.16.5 & 1.17.x)  
Loom: from 0.5 to 0.9  
Java: Oracle JDK 16.0.1 *or* AdoptOpenJDK 16.0.1.9  
Gradle: 7.0.2 Binary from wrapper  

build.gradle: [Ubuntu Pastebin](https://paste.ubuntu.com/p/ky467sjmzf/)  
settings.gradle:  
```gradle
pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

buildscript.dependencies {
    classpath 'net.fabricmc:tiny-remapper:0.4.2'
}
```  

StackTrace: [Ubuntu Pastebin](https://paste.ubuntu.com/p/kX7M8wKfwh/)

I've tried in multiple devices, but I cannot understand why it crashes.  
This repo also have this bug: https://github.com/Featurehouse/sweet_potato-source  
How to trigger: use IntelliJ IDEA's Gradle Sync.

**Comment by Logiquo** [comment] 2021-06-29 08:32
I believe loom will fetch the correct version of tinyremapper, why do you specify it manually?

**Comment by teddyxlandlee** [comment] 2021-06-29 10:51
> I believe loom will fetch the correct version of tinyremapper, why do you specify it manually?

This is not the main point. The most important thing is the `NullPointerException`: `Caused by: java.lang.NullPointerException: Cannot invoke "org.gradle.internal.resource.metadata.ExternalResourceMetaData.getSha1()" because "metaData" is null`. See full details in [`build.gradle`](https://paste.ubuntu.com/p/ky467sjmzf/) and the stack trace.

**Comment by modmuss50** [comment] 2021-06-29 10:53
Are you running it through intelij here?

**Comment by teddyxlandlee** [comment] 2021-06-29 10:53
The error stops me from building my own mod. I've already tried to delete all my `.gradle` caches, but it did not work.

**Comment by teddyxlandlee** [comment] 2021-06-29 10:53
> Are you running it through intelij here?

Both IntelliJ and command line are tried

**Comment by modmuss50** [comment] 2021-06-29 10:55
Can you run `./gradlew build --refresh-dependencies` throught the commandline and see if that fixes it? If not can you post the log from that.

**Comment by teddyxlandlee** [comment] 2021-06-29 10:58
> 
> 
> Can you run `./gradlew build --refresh-dependencies` throught the commandline and see if that fixes it? If not can you post the log from that.

~~Executing...~~  
[Here](https://paste.ubuntu.com/p/ngdkWg7HGQ/), still crashes. @modmuss50

**Comment by modmuss50** [comment] 2021-06-29 11:31
Can you run the same again with --stacktrace as well? This looks similar to the outdated intelijj crash but im not sure.

**Comment by teddyxlandlee** [comment] 2021-06-29 11:50
> 
> 
> Can you run the same again with --stacktrace as well? This looks similar to the outdated intelijj crash but im not sure.

https://paste.ubuntu.com/p/kGyZ5bghY6/

**Comment by liach** [comment] 2021-06-29 12:46
Make sure you use loom 0.8, like 0.8.12. I had the same problem with fabric api before, and bumping to 0.8 fixes the problem @teddyxlandlee

**Comment by teddyxlandlee** [comment] 2021-06-29 23:18
> 
> 
> Make sure you use loom 0.8, like 0.8.12. I had the same problem with fabric api before, and bumping to 0.8 fixes the problem @teddyxlandlee

Tried 0.8.  
0.7 is the recommended version for 1.16.x development, however. (although I use OpenJDK 16) So 0.7 is of course a LTS and the problem should be fixed in 0.7. @liach @modmuss50

**Comment by teddyxlandlee** [comment] 2021-06-30 00:29
Tried `0.8.12` just now. Same error & log.

**Comment by liach** [comment] 2021-06-30 01:25
hmm, is it because your maven has some problem with sha1? see https://github.com/COVID-Trump/mvn/tree/master/org/featurehouse/asm/asm-comparator-api/0.1.2 as in the stacktrace, it says this is the error-causing dependency

**Comment by teddyxlandlee** [comment] 2021-07-01 02:16
There is no problem with COVID-Trump maven.  
The log also says it cannot remap fabric-loader-0.11.6, either.

**Comment by liach** [comment] 2021-07-01 02:34
Does it crash if you remove tiny remapper from the buildscript dependencies?

**Comment by teddyxlandlee** [comment] 2021-07-02 23:45
> Does it crash if you remove tiny remapper from the buildscript dependencies?

Yes.

**Comment by liach** [comment] 2021-07-03 00:52
does any of your teammates have the problem? this is quite clueless

**Comment by teddyxlandlee** [comment] 2021-07-03 06:49
> does any of your teammates have the problem? this is quite clueless

My teammates work for textures and websites, etc. They do not deal with Java code very often.  
  
However, _me_ tried on multiple devices with the very same issue.

**Comment by teddyxlandlee** [comment] 2021-07-03 06:52
~~I don't know if it gets solved with Java 8 -- as a "modern" developer on 1.16+, I have to use 16.~~

**Comment by liach** [comment] 2021-07-03 13:27
@teddyxlandlee Can you make a minimal setup to reproduce this problem?

I tried `git clone -b 21w05a https://github.com/Featurehouse/sweet_potato-source`, then `cd sweet_potato-source`, and run `./gradlew build`. The task `:remapSourcesJar` completed successfully for me.

Like you can create a new repo that will have this issue, and tell me which branch to clone. You can set the gradle wrapper in the setup to the version that will cause bugs with `./gradlew wrapper --gradle-verion <your gradle version>`

**Comment by amitojsingh366** [comment] 2021-07-03 23:11
i have the same issue
https://pastebin.com/wBZ9knya

**Comment by liach** [comment] 2021-07-05 08:54
Hmm, maybe loom is creating an invalid ivy repository. Need to check where it creates any ivy repository

**Comment by liach** [comment] 2021-07-05 08:57
Hmm, this might be related to #400 or #407, but why would this break for loom 0.5. Maybe related to the modImplementation configuration

**Comment by modmuss50** [comment] 2021-07-05 09:15
I thought it could have been due to https://github.com/FabricMC/fabric-loom/commit/927180e36b8ec957c0271fc122da9c92ebc04304 but that wont explain why it happens on legacy loom versions.

I tried fixing it here: https://github.com/FabricMC/fabric-loom/commit/3a51777b4bbb9b27bcb5cfd8fc7b0f66660e6f62 but this just seems to have moved the errro elsewhere.

**Comment by liach** [comment] 2021-07-05 09:21
A thing of note is that the ivy resolution is using `AbstractRepositoryMetadataSource`, while 2 ivy declarations in loom requires use of artifact metadata source, [which](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultArtifactMetadataSource.java) is not a subclass.

**Comment by teddyxlandlee** [comment] 2021-07-09 09:46
**Update**: All of my tests were processed on my **exFAT** USB disk. No problems on NTFS. No problems with non-Fabric gradle projects. Is ~~Tiny Remapper~~ or Gradle itself incompatible with exFAT **file system**?  
~~Let me try to use FabricMC/TinyRemapper to remap jars on my USB disk.~~  
On my USB disk, I tried this: `java -jar tiny-remapper-0.4.2-fat.jar minecraft-1.16.5-merged.jar minecraft-1.16.5-intermediary.jar 1.16.5.tiny official intermediary` and succeeded with `Finished after 9953.32 ms.`.  
So this may be an issue between **Gradle** (or loom itself) and **exFAT file system**

**Comment by liach** [comment] 2021-07-09 16:19
Hmm, my suggestion is that you make a basic gradle project (like one created by an IDE by default, include wrapper so you can run commands more easily) and include this publishing stuff:

add this to the beginning of `build.gradle`
```gradle
plugins {
    id 'maven-publish'
}
```

and this to the end of build.gradle
```gradle 
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = uri("file:///E:/test-folder") // assume your fat file system USB is drive E
            name = "test"
        }
    }
}
```

Write some code in your project, like a hello world main.
Then I think you can run `./gradlew build publishMavenJavaToTestRepository` to test if it's a gradle problem.

**Comment by modmuss50** [comment] 2021-07-16 22:29
Thats great to hear @teddyxlandlee When I get a chance ill try and get setup with a way to test with an exFAT partition. Thanks for looking into it 👍

Edit: Update, I was able to reproduce this on an exFAT partition.

**Comment by modmuss50** [comment] 2021-07-17 00:30
This appears to be a bug in gradle's native code here:

https://github.com/gradle/native-platform/blob/cfe37a669f31f4b5b8b252462a0b221e054b4a19/native-platform/src/main/cpp/win.cpp#L135-L142

This is becuase on a FAT file stystem GetFileInformationByHandleEx fails with error ERROR_INVALID_PARAMETER.

I have a found a few examples of other projects working around this:

https://github.com/golang/go/commit/e4535772ca3f11084ee5fa4d4bd3a542e143b80f
https://github.com/coreutils/gnulib/blob/master/lib/stat-w32.c#L218-L219

I was also able to reproduce this by building a minimal c++ test case based off the gradle code.

```c++
#include <iostream>
#include <windows.h>

int main()
{
    DWORD dwFlagsAndAttributes = FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAG_OPEN_REPARSE_POINT;
    HANDLE fileHandle = CreateFileW(
        LR"(G:\fabric-example-mod-1.17\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_17_1_17_build_13_v2\net\fabricmc\fabric-api\fabric-api\0.36.0+1.17\fabric-api-0.36.0+1.17.pom)",
        GENERIC_READ,
        FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE,
        NULL,
        OPEN_EXISTING,
        dwFlagsAndAttributes,
        NULL
    );

    if (fileHandle == INVALID_HANDLE_VALUE) {
        DWORD error = GetLastError();
        std::cout << "not ok!" << std::endl;
        return error;
    }

    BY_HANDLE_FILE_INFORMATION fileInfo;
    BOOL ok = GetFileInformationByHandle(fileHandle, &fileInfo);
    if (!ok) {
        DWORD error = GetLastError();
        CloseHandle(fileHandle);
        return error;
    }

    FILE_ATTRIBUTE_TAG_INFO fileTagInfo;
    BOOL ok = GetFileInformationByHandleEx(fileHandle, FileAttributeTagInfo, &fileTagInfo, sizeof(fileTagInfo));
    if (!ok) {
        DWORD error = GetLastError();
        CloseHandle(fileHandle);
        std::cout << "not ok!" << std::endl;
        return error;
    }

    CloseHandle(fileHandle);

    std::cout << "ok" << std::endl;
}
```

I will look into making a bug report and a pull request to gradle to fix this issue once I have had a chance to look over it a bit more at a sensible time of day. For now the workaround is to not use FAT file systems.

Big thanks to @teddyxlandlee for figuring out it was based on the file system as this unlocked the key to being able to get a debugger in there, and I would have never been able to find it without that information.

**Comment by modmuss50** [comment] 2021-07-17 00:36
Looks like there is a 4 hour old PR fixing this issue: https://github.com/gradle/native-platform/pull/288

I should have looked there before diving into this, was fun anyway.

**Comment by amitojsingh366** [comment] 2021-07-17 09:56
wow great to hear that this is already being resolved! thanks @modmuss50 and all the others for your help!

**Comment by modmuss50** [comment] 2021-07-20 07:44
This should be fixed in the latest [gradle nightly](https://gradle.org/nightly/) build. I can test it later and run loom's automated test suite against it, but I'd expect there to be no issues.

**Comment by modmuss50** [comment] 2021-07-20 08:34
I have confimed this to be fixed on the latest nightly version of gradle.

**Closed as completed by modmuss50** 2021-07-20 08:34 UTC
Labels: bug
