### ISSUE TITLE
"File already in use" errors in some cases

### ISSUE THREAD

**Issue by coderbot16** [FabricMC/fabric-loom#369] opened 2021-03-25 23:21 UTC
I have not observed this issue myself, but if you search for `gradlew stop` in the Fabric discord you can see many instances of people encountering this error. If there is a way for Loom to handle this better or provide nicer diagnostics, that would be very nice.

**Comment by modmuss50** [comment] 2021-03-25 23:27
This has been a common issue for ages, it used to be much much worse however. Tracking down the cause of them is a struggle. What would help is people reporting the issue when it happens with a full --stracktrace log so we can try and figure out patterns to where the most common causes of it are. This is made even harder by the cause of the issue is usually a previous run but then getting a stacktrace only happens after a re-run in a bad state.

Another option would be to try and stop the deamon after a failiure? I'm not aware of a nice way to do this.

If someone can reproduce these issues that would also be great help, even better if we could write a unit test to prove it.

**Comment by frqnny** [comment] 2021-06-11 16:12
Well it normally happens after I run Minecraft then attempt gradlew genSources. In fact, it always happens when I do that. 
https://gist.github.com/frqnny/68839aef1087bb8fe72d3c69066b7d11

**Comment by frqnny** [comment] 2021-06-11 16:26
https://scans.gradle.com/s/wpyi6fwm3wmje Here is a scan to help you.

**Comment by frqnny** [comment] 2021-06-11 16:37
I think I know why it happens. In LineNumberRemapper#process, it will attempt to do this:
`if (parent != null) {
                    Files.createDirectories(parent);
                }`

But Files#createDirectories says in the javadoc that it will throw the FileAlreadyExistsException if the path already exists but it is not a directory, according to the javadoc.

I think we can try to replace it with 
`parent.toFile().getParentFile().mkdirs();`
Which might be a safer implementation? 

Edit: ignore my BS up there I found the issue.

**Comment by modmuss50** [comment] 2021-06-11 23:26
I have spent qutie some time looking into this, and have been able to reproduce it via a unit test, making it much easier to diagnose.

It seems like the Java Compiler is keeping the minecraft jar open:

![](https://i.imgur.com/qykbtAS.png)

File open stacktrace: https://gist.github.com/modmuss50/92e07b050a80c10b518fa32576cef4b1

One easy workaround is to add the following to your build.gradle

```groovy
tasks.withType(JavaCompile) {
    options.fork = true
}
```

This all seems to stem from the fact that minecraft (and all of its libs) are on the annotation processor classpath: https://github.com/FabricMC/fabric-loom/blob/dev/0.8/src/main/java/net/fabricmc/loom/build/mixin/AnnotationProcessorInvoker.java#L95-L100 Im not 100% sure that this is needed but it seems quite delibrate and would need more testing without it.

The easy solution would be for loom to fork the compiler, and this might not be a bad idea for it to do anyway, but it would be nice to get the bottom of this.

**Comment by Logiquo** [comment] 2021-08-22 03:52
> Im not 100% sure that this is needed but it seems quite delibrate and would need more testing without it.

This is for MCE to get the mapping from its parent for the inherited method. Such information cannot be obtained without MC jar.

**Comment by modmuss50** [comment] 2021-12-30 00:30
Not seen this for a while, the issue I was talking about was fixed in Mixin.

**Closed as completed by modmuss50** 2021-12-30 00:30 UTC
Labels: bug
