### ISSUE TITLE
Non-Java sources are excluded from source jar after remapping

### ISSUE THREAD

**Issue by magneticflux-** [FabricMC/fabric-loom#126] opened 2019-08-06 22:05 UTC
The `remapSourcesJar` task only copies files ending in `*.java`. For non-Java mods, this means the source jar is incomplete.

Even if the sources can't be remapped, it may be useful to include them as-is.

**Comment by JamiesWhiteShirt** [comment] 2019-08-07 15:25
Can be considered a duplicate of #118 

The fundamental issue in this case is that the source jar will not truly match. We could make the task just copy them like resources, but the mappings in the source might not match the binaries. We should be looking into supporting source remapping for other languages that people use in fabric (kotlin or scala).

**Comment by RedstoneParadox** [comment] 2019-08-14 18:24
It really seems like Loom adding direct support for other languages seems out of scope - especially when the rest of the main Fabric toolchain only supports Java, not to mention that only a small portion of mods are actually written in Kotlin or Scala. Rather, Loom should provide an API that the language adapters can use to add support for remapping sources.

**Comment by magneticflux-** [comment] 2019-08-14 23:13
The rest of the main Fabric toolchain supports JVM languages, not just Java. There's no way to even _restrict_ support to just Java since everything gets reduced to JVM bytecode anyway.

The Kotlin and Scala libraries are only to bundle their respective standard libraries in an accessible format and provide minor QoL improvements. It's entirely possible to shade the standard libraries in your own mod and reference the JVM names for your Kotlin and Scala classes, it's just not recommended or very compatible.

I think the authors of those libraries should share their opinions as well. @NikkyAI @modmuss50 @shadowfacts

**Comment by NikkyAI** [comment] 2019-08-15 08:26
the problem of integrating loom with language modules is.. 
those are just for fabric-loader QoL
adding extra libraries to loom is not a good idea imho
and loom is not modular enough to add a fabric-loom-kotlin plugin or so i think
and loading remapping procedures dynamically from the loader code would be a bad idea too i think

so which one is the least bad option ?

**Closed as completed** 2019-08-23 10:59 UTC
