### ISSUE TITLE
migrateMappings support for kotlin

### ISSUE THREAD

**Issue by walksanatora** [FabricMC/fabric-loom#1034] opened 2024-02-01 20:11 UTC
this is probally a lowest of low issue but. the ability to run migrateMappings on kotlin files would be nice (espically since the template generator allows you to generate with kotlin as a langague)

**Comment by modmuss50** [comment] 2024-02-01 20:16
Yes, this is something I would love to support, however I am not aware of any Kotlin source remapper that would be suitable for use within Loom. 

https://docs.openrewrite.org/ has been noted as a suggestion before, but I haven't looked into it much. I think the next stage for this is for someone to prove that this is a viable solution by hacking it up to remap some Kotlin code.

**Comment by modmuss50** [comment] 2024-03-19 22:29
Duplicate of #286

**Closed as not planned by modmuss50** 2024-03-19 22:29 UTC
