### ISSUE TITLE
Loom 0.11 subproject on Mac: Could not find java-objc-bridge-1.0.0-natives-osx.jar

### ISSUE THREAD

**Issue by The-Fireplace** [FabricMC/fabric-loom#621] opened 2022-04-03 19:21 UTC
Hello, I've run into an issue setting up the MultiLoader template and they suggested this might be an issue with Loom itself.
This does not occur with the standard Fabric setup from FabricMC/fabric-example-mod, so I suspect either something is off with the multiloader setup or the multiloader setup hits some edge case that the example mod does not. Changing the Fabric/build.gradle to use Loom 0.10-SNAPSHOT does not have the issue, so it seems likely that some change happened to introduce this problem with Loom 0.11.

[root build.gradle](https://github.com/jaredlll08/MultiLoader-Template/blob/1.18/build.gradle)
[fabric build.gradle](https://github.com/jaredlll08/MultiLoader-Template/blob/1.18/Fabric/build.gradle)

Specifically, when trying to gradle sync in Idea, I encounter the following error:
```
Starting Gradle Daemon...
Gradle Daemon started in 1 s 446 ms

> Configure project :Common
SpongePowered Vanilla 'GRADLE' Toolset Version '0.2.1-SNAPSHOT'
Targeting Minecraft '1.18.2' on a 'JOINED' platform

> Configure project :Fabric
Fabric Loom: 0.11.32

> Configure project :Forge
WARNING: This project is configured to use the official obfuscation mappings provided by Mojang. These mapping fall under their associated license, you should be fully aware of this license. For the latest license text, refer below, or the reference copy here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md, You can hide this warning by running the `hideOfficialWarningUntilChanged` task
WARNING: (c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here.  Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License Agreement available at https://account.mojang.com/documents/minecraft_eula.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':Fabric:configureClientLaunch'.
> Could not create task ':Fabric:extractNatives'.
   > Could not create task of type 'ExtractNativesTask'.
      > Could not resolve all files for configuration ':Fabric:minecraftNatives'.
         > Could not find java-objc-bridge-1.0.0-natives-osx.jar (ca.weblite:java-objc-bridge:1.0.0).
           Searched in the following locations:
               https://repo.maven.apache.org/maven2/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
```

jaredlll08/MultiLoader-Template#11

Let me know any suggestions or if you need any additional details.

**Comment by modmuss50** [comment] 2022-04-03 21:25
Are you using a arm64 (Apple Slicone mac?) as loom has special support for that. from the logs I dont think you are?

It doesnt seem to trying to use the mojang maven to find your natives. As you said you cannot reproduce it with the standard setup I have a worry its caused by one of the other minecraft related plugins. Can you try without FG and without VG to see if you can track it down to a clash with a specific project.

I know of people who have successfuly used 0.11 loom with this template on a arm64 mac.

**Comment by The-Fireplace** [comment] 2022-04-03 21:45
No, this is not an arm64 Mac. It's a 2018 Mac mini.

I commented out FG and VG related code, and the problem continued. Then I went to the root build.gradle's `subprojects` block and commented out `repositories { ... }` and that seemed to resolve it (though it caused other problems, so it could be that they just happened to get hit before this issue)

**Comment by The-Fireplace** [comment] 2022-04-03 21:53
In fact, once I enabled FG and VG again, it seems to sync with Loom 0.11 without issues. So I suspect it's the subprojects repositories block that breaks it.

**Comment by jaredlll08** [comment] 2022-04-03 21:59
I believe the reason we use the subproject repositories block like that was because we ran into an issue where we couldn't declare multiple repository blocks for each subproject, but it can be relooked at to figure out why.

Does Loom inject any repositories / touch the repository block at all?

**Comment by modmuss50** [comment] 2022-04-03 22:18
Yes, https://github.com/FabricMC/fabric-loom/blob/dev/0.12/src/main/java/net/fabricmc/loom/LoomRepositoryPlugin.java

Almost seems like looms repos aren’t getting applied for some reason.

**Comment by jaredlll08** [comment] 2022-04-05 20:08
@The-Fireplace can you add:
```groovy
    task listrepos {
        doLast {
            println "{project.name} Repos:"
            project.repositories.each {
                if(!it.class.getSimpleName().equals("GradleRepositoryAdapter")){
                    println "Name: " + it.name + "; url: " + it.url
                }
            }
        }
    }
```
into the root `subprojects` block, and then run `gradle listrepos` and give the results

@modmuss50 In this commit, you mention fixing the issue for arm64 MacOS, but in your check here:
https://github.com/FabricMC/fabric-loom/commit/316f9d95081c0d9ba5c8d8ee5db4fe80512ec5d7#diff-be6161787a9734d80360abe16fdf4201082326f2f495012c02757e400e9d081eR91
you are only checking if `isMacOS`, not if it is arm, could that possibly be the issue / a bug?

**Comment by modmuss50** [comment] 2022-04-05 20:11
Possibly yes, overrideLWJGL should be false tho as it’s a none arm mac.

**Comment by The-Fireplace** [comment] 2022-04-05 22:32
```
./gradlew listrepos
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

> Configure project :Common
SpongePowered Vanilla 'GRADLE' Toolset Version '0.2.1-SNAPSHOT'
Targeting Minecraft '1.18.2' on a 'JOINED' platform

> Configure project :Fabric
Fabric Loom: 0.11.32

> Configure project :Forge
WARNING: This project is configured to use the official obfuscation mappings provided by Mojang. These mapping fall under their associated license, you should be fully aware of this license. For the latest license text, refer below, or the reference copy here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md, You can hide this warning by running the `hideOfficialWarningUntilChanged` task
WARNING: (c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here.  Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License Agreement available at https://account.mojang.com/documents/minecraft_eula.

> Task :Common:listrepos
{project.name} Repos:
Name: MavenRepo; url: https://repo.maven.apache.org/maven2/
Name: Sponge / Mixin; url: https://repo.spongepowered.org/repository/maven-public/
Name: BlameJared Maven (CrT / Bookshelf); url: https://maven.blamejared.com
Name: VanillaGradle Global Cache; url: file:/Users/lance/.gradle/caches/VanillaGradle/v2/jars/
Name: VanillaGradle Project Cache; url: file:/Users/lance/IdeaProjects/Minecraft/MultiLoader-Template/.gradle/caches/VanillaGradle/v2/jars
Name: minecraft; url: https://libraries.minecraft.net/
Name: forge; url: https://maven.minecraftforge.net/

> Task :Fabric:listrepos
{project.name} Repos:
Name: MavenRepo; url: https://repo.maven.apache.org/maven2/
Name: Sponge / Mixin; url: https://repo.spongepowered.org/repository/maven-public/
Name: BlameJared Maven (CrT / Bookshelf); url: https://maven.blamejared.com
Name: UserLocalRemappedMods; url: file:/Users/lance/IdeaProjects/Minecraft/MultiLoader-Template/.gradle/loom-cache/remapped_mods/
Name: Fabric; url: https://maven.fabricmc.net/
Name: Mojang; url: https://libraries.minecraft.net/
Name: MavenRepo2; url: https://repo.maven.apache.org/maven2/
Name: ivy; url: file:/Users/lance/.gradle/caches/fabric-loom/
Name: ivy2; url: file:/Users/lance/IdeaProjects/Minecraft/MultiLoader-Template/.gradle/loom-cache/

> Task :Forge:listrepos
{project.name} Repos:
Name: MavenRepo; url: https://repo.maven.apache.org/maven2/
Name: Sponge / Mixin; url: https://repo.spongepowered.org/repository/maven-public/
Name: BlameJared Maven (CrT / Bookshelf); url: https://maven.blamejared.com
Name: maven; url: https://maven.minecraftforge.net/
Name: maven2; url: https://libraries.minecraft.net/
Name: MavenRepo2; url: https://repo.maven.apache.org/maven2/

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 12s
3 actionable tasks: 3 executed
```

**Comment by jaredlll08** [comment] 2022-04-05 22:58
So unless I'm mistaken, it's adding all the repos that are defined here https://github.com/FabricMC/fabric-loom/blob/dev/0.12/src/main/java/net/fabricmc/loom/LoomRepositoryPlugin.java#L62-L106

So maybe there is something else going on?

**Comment by The-Fireplace** [comment] 2022-04-06 00:52
Perhaps. I retried the sync with the `--debug` option, maybe this log output has more details that are useful:
https://gist.github.com/The-Fireplace/52e46da20ace00b58836ec476e5ba6df

If that's too much, I can do one with `--info` instead.

**Comment by modmuss50** [comment] 2022-04-06 09:46
I wonder if gradle is trying to be clever by only looking for the `natives-osx` on maven central as the default jar does exist on cental. Mojang created the split native jars, thus they dont exist on central. (This was undone in 1.19 snapshots).

Loom adds the Mojang repo before maven central, if we assume (Im unsure off the top of my head if this is defined behaviour) they are ordered, with only loom present it will first try the Mojang repo when resolving libraries, and find objc bridge there, and the correct natives.

In your template here: <https://github.com/jaredlll08/MultiLoader-Template/blob/1.18/build.gradle#L28> You add maven central first, could you try adding the mojang repo `https://libraries.minecraft.net/` before central?

Edit: You may need to refresh deps to break any caching around this.

**Comment by jaredlll08** [comment] 2022-04-06 14:16
Going to need @The-Fireplace to test that since I don't have access to a mac.

I wonder if it may be worth adding an exclude filter (https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:declaring-repository-filter) to central to not get that artifact from there.

**Comment by The-Fireplace** [comment] 2022-04-06 17:46
> I wonder if gradle is trying to be clever by only looking for the `natives-osx` on maven central as the default jar does exist on cental. Mojang created the split native jars, thus they dont exist on central. (This was undone in 1.19 snapshots).
> 
> Loom adds the Mojang repo before maven central, if we assume (Im unsure off the top of my head if this is defined behaviour) they are ordered, with only loom present it will first try the Mojang repo when resolving libraries, and find objc bridge there, and the correct natives.
> 
> In your template here: https://github.com/jaredlll08/MultiLoader-Template/blob/1.18/build.gradle#L28 You add maven central first, could you try adding the mojang repo `https://libraries.minecraft.net/` before central?
> 
> Edit: You may need to refresh deps to break any caching around this.

I think you're right about Gradle trying to be clever. Adding the mojang repo before mavenCentral like you suggested fixes the problem.

**Comment by modmuss50** [comment] 2022-04-06 17:50
Ok, thats great to know.. don't you love Gradle 🙃 

Loom should really do something about this, at the very least throw a nicer error. Not a loom bug, but something loom can improve on. 1.19 will fix this as well.

**Closed as completed** 2022-04-13 22:35 UTC
Labels: enhancement
