### ISSUE TITLE
Configuration lock issue with restarting the game in IDEA

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#703] opened 2022-08-10 20:43 UTC
## Reproduction
1. Run game through IDEA
2. Restart the game with the restart button (stop icon with arrow around it)

## Result
> Failed to release configuration lock

because the file is in use by another process (I'm on Windows). This doesn't happen always though, and I can't reproduce it consistently for some reason.

**Comment by modmuss50** [comment] 2022-08-10 21:11
If you can reproduce it with --debug or find the stacktrace somehow that would be great. 🤔

**Comment by modmuss50** [comment] 2022-08-14 11:04
I am unable to reproduce this on windows. I have tried using the idea run config, and running using the gradle task. Are you using a single project setup? Or a multi project setup?

**Comment by Juuxel** [comment] 2022-08-14 11:23
In my case it was a single project setup. I'm not sure what I did to trigger it, could've been a cancelled/failed build for example.

**Comment by modmuss50** [comment] 2022-08-17 21:59
Sounds like this may be fixed. If anyone has any similar issues let me know ASAP.

**Comment by IMB11** [comment] 2022-08-19 16:44
Im now encountering this?

```log
17:43:15: Executing 'runClient'...


> Configure project :
Fabric Loom: 0.13.12

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'MobArmor'.
> Failed to release project configuration lock

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
17:43:17: Execution finished 'runClient'.

```

**Comment by IMB11** [comment] 2022-08-19 16:44
I am unable to delete the lock file in windows explorer too

**Comment by modmuss50** [comment] 2022-08-19 16:47
Have you got a way to reproduce this? Im lost as to how it’s even locked in the first place. Loom only creates and deletes the file, never writes to it. 🤔

**Comment by IMB11** [comment] 2022-08-19 18:34
Closing my IDE then deleting it manually seems to fix it. I have no clue how to reproduce it other than pressing this on the Minecraft configurations ![](https://oh.why-am-i-he.re/5F9ku_n80.png)

**Comment by IMB11** [comment] 2022-08-19 18:34
Could IDEA be reading something whilst gradle does it stuff?

**Comment by IMB11** [comment] 2022-08-19 19:07
Figured it out! IntellIJ has a "filesystem watcher" daemon process that opens files up for a split second to verify the contents (and update it in the IDE file list) It seems it is opening the lock file as gradle tries to delete it, meaning gradle can't delete it.

**Comment by IMB11** [comment] 2022-08-19 19:07
![](https://oh.why-am-i-he.re/5F9sWYXtr.png)

killing the watcher fixes the error.

**Comment by modmuss50** [comment] 2022-08-19 21:26
Thats great, I will try moving it out of the project directory to see if that helps. Thanks 👍

**Comment by IMB11** [comment] 2022-08-19 21:28
To be honest, intellIJ shouldn't be watching files in `.gradle` in the first place

**Comment by modmuss50** [comment] 2022-08-22 19:43
Pushed another fix for this that moves it out of the project dir. Again please let me know of any issues 👍

**Closed as completed** 2022-08-22 19:43 UTC
