### ISSUE TITLE
Feature: Ability to inject interfaces with generic types

### ISSUE THREAD

**Issue by TropheusJ** [FabricMC/fabric-loom#932] opened 2023-07-16 00:19 UTC
Injected interfaces can only be the raw type, no generics. 
I wanted to add a `getNullable` to `DefaultedRegistry<T>`, by injecting `DefaultedRegistryExtensions<T>`. However, this is not possible, and only a raw type can be injected. This makes the method only return `Object`, which kind of ruins it.

**Comment by modmuss50** [comment] 2023-11-10 11:03
The plan was to handle this with classtweaker.

**Comment by modmuss50** [comment] 2023-11-10 11:14
Duplicate of #597

**Closed as not planned by modmuss50** 2023-11-10 11:14 UTC
